export const production = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","NEXT_PUBLIC_SITE_URL":"","PEXELS_API_KEY":""};
export const development = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","NEXT_PUBLIC_SITE_URL":"","PEXELS_API_KEY":""};
export const test = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","NEXT_PUBLIC_SITE_URL":"","PEXELS_API_KEY":""};
